settings:
  APP_DISPLAY_NAME: Element X Search
  PRODUCTION_APP_NAME: Element X Search
  APP_GROUP_IDENTIFIER: group.com.pavzagor.elementxsearch
  BASE_BUNDLE_IDENTIFIER: com.pavzagor.elementxsearch
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: ""
  IS_NIGHTLY_BUILD: false
